# Auto-generated by Raaghu Harness
# Objective: build a .html landing page, for this harness, which will give all the required data and visusals and then save this project in the current repo named as "landing.html"

print("Hello from auto-generated script for: build a .html landing page, for this harness, which will give all the required data and visusals and then save this project in the current repo named as "landing.html"")
