import os
import subprocess
import time

def run_autonomous_task(objective):
    print("\n" + "=" * 60)
    print(f"[RAAGHU HARNESS] Executing Objective: \"{objective}\"")
    print("=" * 60 + "\n")
    
    # Step 1: Conductor / Brain plans the filename based on objective
    print("[CONDUCTOR] Analyzing objective and generating file structure...")
    time.sleep(0.4)
    
    # Generate a clean filename based on the objective words
    clean_name = "".join([c if c.isalnum() else "_" for c in objective.lower()]).strip("_")
    filename = f"{clean_name[:25]}_output.py"
    file_content = f"# Auto-generated by Raaghu Harness\n# Objective: {objective}\n\nprint(\"Hello from auto-generated script for: {objective}\")\n"
    
    print(f"[BRAIN] Creating file: {filename}")
    with open(filename, "w") as file_obj:
        file_obj.write(file_content)
    time.sleep(0.4)
    
    # Step 2: Bouncer / Guardrails check safety
    print("[BOUNCER] Scanning code safety... Passed.")
    time.sleep(0.4)
    
    # Step 3: Tool Registry executes Git commands to push it to GitHub
    print(f"[TOOL REGISTRY] Staging, committing, and pushing '{filename}' to GitHub...")
    try:
        subprocess.run(["git", "add", filename], check=True)
        subprocess.run(["git", "commit", "-m", f"feat: autonomous agent generated {filename} for objective: {objective}"], check=True)
        subprocess.run(["git", "push"], check=True)
        print(f"\n[SUCCESS] File '{filename}' successfully created and pushed to GitHub!")
    except Exception as e:
        print(f"\n[ERROR] Git push failed: {e}")
        
    print("=" * 60 + "\n")

def main():
    print("==================================================")
    print("   RAAGHU AI AGENT HARNESS (Autonomous Mode)      ")
    print("==================================================")
    print("Type your objective and watch it build & push to GitHub.")
    print("Type 'exit' or 'quit' to close.\n")
    
    while True:
        try:
            objective = input("raaghu (auto)> ").strip()
            if not objective:
                continue
            if objective.lower() in ["exit", "quit"]:
                print("Shutting down raaghu harness. Goodbye!")
                break
            run_autonomous_task(objective)
        except KeyboardInterrupt:
            print("\nShutting down raaghu harness. Goodbye!")
            break

if __name__ == "__main__":
    main()
